### ISSUE TITLE
为何时区要写死成重庆？

### ISSUE THREAD

**Issue by vision9527** [smartwalle/alipay#103]
在alipay.go文件New方法中：

// New 初始化支付宝客户端
// appId - 支付宝应用 id
// privateKey - 应用私钥，开发者自己生成
// isProduction - 是否为生产环境，传 false 的时候为沙箱环境，用于开发测试，正式上线的时候需要改为 true
func New(appId, privateKey string, isProduction bool) (client *Client, err error) {
	location, err := time.LoadLocation("Asia/Chongqing")
	if err != nil {
		return nil, err
	}
        .........
}

**Comment by smartwalle** [comment]
之前有网友反馈服务器放在国外的话，时区上有问题。

**Comment by a7505553** [comment]
写死时区有问题 。 线上docker使用的Asia/Shanghai 时区， 实例化客户端的时候就会报unknown time zone Asia/Chongqing。

**Comment by smartwalle** [comment]
可以改的

**Comment by smartwalle** [comment]
> 写死时区有问题 。 线上docker使用的Asia/Shanghai 时区， 实例化客户端的时候就会报unknown time zone Asia/Chongqing。

初始化的时候，有一组可选参数列表，你看一下代码，有改时区的选项

**Comment by tanqiuqiang** [comment]
选项没有用，选择重庆时区的时候报错，就直接返回了

**Comment by smartwalle** [comment]
> 选项没有用，选择重庆时区的时候报错，就直接返回了

能否描述清楚一些

**Comment by smartwalle** [comment]
已将默认时间调整为 time.Local, 需要指定其它时区信息的可以在初始化的时候通过  WithTimeLocation 函数指定。
