### ISSUE TITLE
能搞一些使用的案例demo吗？

### ISSUE THREAD

**Issue by opcache** [smartwalle/alipay#105]
能搞一些使用的案例demo吗？只要配置支付宝参数，启动后，有一个小网页，点击各种支付的案例demo?方便新手

**Comment by smartwalle** [comment]
test 里面有示例

**Comment by lijinghuatongxue** [comment]
> 能搞一些使用的案例demo吗？只要配置支付宝参数，启动后，有一个小网页，点击各种支付的案例demo?方便新手

同求

**Comment by chengjoey** [comment]
[沙箱测试demo](https://github.com/chengjoey/alipay-demo)我写了一个沙箱测试的demo可供大家参考使用
