### ISSUE TITLE
安卓调用sdk->支付宝错误 ALIN10146 排查 验签失败,应该是不能传空

### ISSUE THREAD

**Issue by xujiangtao0207** [smartwalle/alipay#109]
https://github.com/smartwalle/alipay/blob/31701f45422680e3433bd2e2deb1b91ee0066233/trade_type.go#L489

	if this.AppAuthToken != "" {
		m["app_auth_token"] = this.AppAuthToken
	}

**Comment by smartwalle** [comment]
已统一判断并过滤该参数的空值
