### ISSUE TITLE
现金红包有集成进来吗

### ISSUE THREAD

**Issue by fjnpzjx** [smartwalle/alipay#110]
你好，可以帮我看一下我的问题不，具体描述我写在二楼了，刚从PHP转到go，遇到问题实在没有头绪😂

**Comment by fjnpzjx** [comment]
你好，我在你的项目基础上集成了alipay.fund.trans.app.pay(现金红包无线支付接口)，但是返回了一个奇怪的错误
`
Post"mobilecashier.d6243.alipaydev.com:12200?alipay_exterface_invoke_assign_target=invoke_97be59ef7b36643d8586d30456098d12&alipay_exterface_invoke_assign_sign=_z_u_ie_n_qy_d_n_u1i8t11_x6_e_r_e_g_a0gss_cy_zo0_j_p7_h_p_hul_j_v%2Boc9nwul_r_chw%3D%3D": unsupported protocol scheme "mobilecashier.d6243.alipaydev.com"`

阿里云上也有人提相似的问题，但是好像没有解决，这个是阿里云的链接
[https://developer.aliyun.com/ask/255578?spm=5176.12901015.0.i12901015.68d6525c22jfhF](url)

但是我集成其他接口都可以正常请求并且正常返回，只是提示参数格式错误之类的，不会有这样看不懂的错误

如果你有时间的话，可以看一下吗，是不是也会出现这个问题

我搞了好几天了，网上也找不到其他的资料

**Comment by smartwalle** [comment]
你看一下你发的那个链接里面最后一楼的内容，然后参照项目中的 TradeAppPay 方法进行处理试一下。
