### ISSUE TITLE
APP支付-商家订单参数异常

### ISSUE THREAD

**Issue by venuses** [smartwalle/alipay#111]
APP支付出现如下错误
![image](https://user-images.githubusercontent.com/14290858/81285833-b08ee080-9092-11ea-8ccd-509c12fee50a.png)

**Comment by smartwalle** [comment]
我没有 APP 环境，你这边方便调试一下吗

**Comment by venuses** [comment]
找到问题了，多了一个签名参数 app_auth_token 导致签名错误
```go

func (this TradeAppPay) Params() map[string]string {
	var m = make(map[string]string)
	// m["app_auth_token"] = this.AppAuthToken // 不需要传递此参数
	m["notify_url"] = this.NotifyURL
	return m
}
```

**Comment by smartwalle** [comment]
你用的是那一个版本，这个参数我是有过滤掉空值的。  https://github.com/smartwalle/alipay/blob/dbf8ba44e33053ee2c95f27b4f625361242d33c5/alipay.go#L235

**Comment by venuses** [comment]
3.1.1 版本，这个版本刚看了，是没有过滤空值的。这里的版本号不是按顺序来的吗
![image](https://user-images.githubusercontent.com/14290858/81363935-0f963900-9117-11ea-8a21-9e9b09852a33.png)

**Comment by smartwalle** [comment]
我重新提交了 3.1.2 版本，更新一下就好了

**Comment by venuses** [comment]
> 你用的是那一个版本，这个参数我是有过滤掉空值的。
> 
> https://github.com/smartwalle/alipay/blob/dbf8ba44e33053ee2c95f27b4f625361242d33c5/alipay.go#L235

这里是否应该应该改一下条件，用逻辑or来剔除其他的空值参数。
