### ISSUE TITLE
支付宝单笔转账接口升级

### ISSUE THREAD

**Issue by mikenut** [smartwalle/alipay#113]
目前支付宝对单笔转账接口进行了升级更新，[新接口地址](https://opendocs.alipay.com/apis/api_28/alipay.fund.trans.uni.transfer)，希望作者跟进。

**Comment by smartwalle** [comment]
我对照了一下参数，没发现有什么变化呀

**Comment by mikenut** [comment]
> 我对照了一下参数，没发现有什么变化呀

变更：[https://opendocs.alipay.com/open/00ou7f](https://opendocs.alipay.com/open/00ou7f)

**Comment by smartwalle** [comment]
这个早就已经更新了呀

**Comment by mikenut** [comment]
对不起，没看到后面的接口
