### ISSUE TITLE
Trade.ExtendParams  被定义成一个string了

### ISSUE THREAD

**Issue by shoaly** [smartwalle/alipay#120]
ExtendParams   其实是一个键值对, 一起json.Marshal(param) 之后传给官方的,  但是现在被定义成一个string, 应该是有bug的. 
比如 一个常规操作是将 sys_service_provider_id 放入 extend_params 当中, 
建议将 这个字段换成 map[string]interface{},   
p.ExtendParams = map[string]string{
    "sys_service_provider_id": pid,
}

**Comment by smartwalle** [comment]
已更新
