### ISSUE TITLE
alipay.fund.trans.uni.transfer(单笔转账接口)已经有更新了

### ISSUE THREAD

**Issue by feige84** [smartwalle/alipay#122]
alipay.fund.trans.toaccount.transfer(单笔转账到支付宝账户接口)
官方说明：目前已对该接口能力做了升级，后续建议调用新接口alipay.fund.trans.uni.transfer，作者能更新一下吗？谢谢。祝工作顺利！

**Comment by smartwalle** [comment]
这个接口是有的
