### ISSUE TITLE
异步通知接口问题

### ISSUE THREAD

**Issue by aveyuan** [smartwalle/alipay#124]
在沙箱环境出现
`2020/10/12 16:47:03 消息通知解析失败alipay: alipay public key not found
`
在正式环境出现
`
2020/10/12 17:17:29 消息通知解析失败40002 - 缺少支付宝公钥证书序列号
`
都是按照demo来的,支付都成功了,回调消息解析失败了.

**Comment by smartwalle** [comment]
沙箱环境那个是因为该环境的通知不支持公钥证书。

生产环境那个你看一下加载证书的那几个方法有没有返回错误。

**Comment by aveyuan** [comment]
谢谢,生产环境就是因为没有加载证书,已经解决啦
