### ISSUE TITLE
異步通知驗簽出現錯誤

### ISSUE THREAD

**Issue by KevinZTW** [smartwalle/alipay#132]
按照 [官方範例 ](https://opendocs.alipay.com/apis/api_1/alipay.trade.app.pay) 調用 VerifyAliNotification 方法出現 illegal base64 data at input byte 3 錯誤，不知道是否是因為 sign 從 request 取出過程中遺漏了 "+" 字元所導致 ? 不知道是否有建議的解決方法嗎?

範例中 sign : WcO+t3D8Kg71dTlKwN7r9PzUOXeaBJwp8/FOuSxcuSkXsoVYxBpsAidprySCjHCjmaglNcjoKJQLJ28/Asl93joTW39FX6i07lXhnbPknezAlwmvPdnQuI01HZsZF9V1i6ggZjBiAd5lG8bZtTxZOJ87ub2i9GuJ3Nr/NUc9VeY=

**Comment by cupen** [comment]
没碰到这个问题。

我在自己的 fork 上加了一个命令行验签工具，也许用得上?
https://github.com/gamedev-embers/alipay/blob/dev/cmd/alipay-sign/main.go
