### ISSUE TITLE
转账接口验签失败

### ISSUE THREAD

**Issue by YinHjie** [smartwalle/alipay#137]
同样的参数，在单独封装的sdk里面AlipayClient.FundTransToAccountTransfer(p)调用是ok的，在业务系统引入sdk后，通过client调用验签失败。请大佬指导一下。
sdk的test测试
`p := FundTransToAccountTransfer{
		OutBizNo:    "shengba3142321423432001",
		TransAmount: "0.1",
		ProductCode: "TRANS_ACCOUNT_NO_PWD",
		BizScene:    "DIRECT_TRANSFER",
		PayeeInfo: PayeeInfo{
			Identity:     "189****689",
			IdentityType: "ALIPAY_LOGON_ID",
			Name:         "xxx",
		},
	}
	rsp, err := AlipayClient.FundTransToAccountTransfer(p)`

业务系统调用
`transfer := &sdk_alipay_transfer.FundTransToAccountTransfer{
			OutBizNo:    "shengba" + time.Now().Format(constants.TIME_YYYYMMDD) + sdk_generate_biz_no.GenerateBizNo(),
			TransAmount: utils.Str2Decimal(withdrawReq.WithdrawAmount).Div(decimal.NewFromInt(1000000)).String(),
			ProductCode: "TRANS_ACCOUNT_NO_PWD",
			BizScene:    "DIRECT_TRANSFER",
		}
		transfer.PayeeInfo.Identity = accountNo
		transfer.PayeeInfo.IdentityType = "ALIPAY_LOGON_ID"
		transfer.PayeeInfo.Name = userName
		qlog.Infof("=====alipay client===", alipayClient)
		transferRsp, transferErr := sdk_alipay_transfer.AlipayClient.FundTransToAccountTransfer(*transfer)`

**Comment by YinHjie** [comment]
证书加载有问题，LoadAppPublicCert，LoadAliPayPublicCert这两个证书加载失败，LoadAliPayRootCert这个倒是正常的

**Comment by zibber2015** [comment]
@YinHjie  请问你解决了没
我的是 LoadAppPublicCert 失败

**Comment by YinHjie** [comment]
你把AppPublicCert这个证书内容原样拷出来用反引号引起来赋给一个变量，AlipayClient.LoadAppPublicCert(AppPublicCert)再用这个方法加载试试看，我的是OK的。

**Comment by zibber2015** [comment]
@YinHjie  谢谢, 我之前支付宝应用加签不是用的csr方式, 我用LoadAppPublicCertFromFile测试是正常的
