### ISSUE TITLE
public key error

### ISSUE THREAD

**Issue by yuzhouisme** [smartwalle/alipay#14]
在收到回调通知验签的过程中，VerifyPKCS1v15报”public key error“。我的ALIPAY_PUBLIC = 支付宝沙盒配置那里的“查看支付宝公钥”，是否还需要对这个公钥进行转换么？

**Comment by yuzhouisme** [comment]
取出相关参数，用支付宝的工具验签是对的，但是代码里就报错误

**Comment by smartwalle** [comment]
你好，获取到支付宝的公钥之后，请将其格式调整为标准的公钥格式，请参考项目中的 alipay_test.go 中的公钥格式进行调整。

**Comment by smartwalle** [comment]
像这种格式

-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2MhEVUp+rRRyAD9HZfiS
g8LLxRAX18XOMJE8/MNnlSSTWCCoHnM+FIU+AfB+8FE+gGIJYXJlpTIyWn4VUMte
wh/4C8uwzBWod/3ilw9Uy7lFblXDBd8En8a59AxC6c9YL1nWD7/sh1szqej31VRI
2OXQSYgvhWNGjzw2/KS1GdrWmdsVP2hOiKVy6TNtH7XnCSRfBBCQ+LgqO1tE0NHD
DswRwBLAFmIlfZ//qZ+a8FvMc//sUm+CV78pQba4nnzsmh10fzVVFIWiKw3VDsxX
PRrAtOJCwNsBwbvMuI/ictvxxjUl4nBZDw4lXt5eWWqBrnTSzogFNOk06aNmEBTU
hwIDAQAB
-----END PUBLIC KEY-----
