### ISSUE TITLE
错误代码 invalid-signature 错误原因: 验签出错，建议检查签名字符串或签名私钥与应用公钥是否匹配

### ISSUE THREAD

**Issue by maxyang107** [smartwalle/alipay#149]
你好作者大佬，我这边在使用的时候，调用支付接口，一直报错 invalid-signature，我排查了支付宝上面的设置，签名结果也跟那个支付宝官方的工具对比了，是一致的，还是报这个错，您有遇到过或者可以帮我解惑吗？

**Comment by jun3372** [comment]
我这边也遇到同一那个的问题不知道该怎么解决

**Comment by Bingle-labake** [comment]
我也遇到这个问题，支付宝的客服折腾几个小时也没解决；通过验签工具，私钥和公钥也是匹配的，一直提示错误代码 invalid-signature 错误原因: 验签出错......
