### ISSUE TITLE
alipay.trade.query (统一收单线下交易查询) 支付宝返回的数据验签

### ISSUE THREAD

**Issue by panjunjie** [smartwalle/alipay#15]
alipay.trade.query (统一收单线下交易查询) 支付宝返回的数据，需不需要验证签名？为了安全起见，希望增加一个函数，把响应的结构体转化成 request 对象，再传入你写好 verify_rsa2 进行验签。

**Comment by panjunjie** [comment]
因为现在一些工具，比如 fiddler ，在网络传输过程中，绕过了 ssl 证书，轻易伪造 支付宝的 响应数据，对数据进行篡改，最后返回给应用的接口，这么一来，就没有什么安全性了。

**Comment by smartwalle** [comment]
已添加对返回数据签名验证，请参考 README 中的 “同步返回验签” 小节。

**Comment by panjunjie** [comment]
@smartwalle 非常感谢
