### ISSUE TITLE
UserCertdocCertverifyConsult 接口缺少AuthToken参数

### ISSUE THREAD

**Issue by HaibaraAi123** [smartwalle/alipay#155]
UserCertdocCertverifyConsult
alipay.user.certdoc.certverify.consult(实名证件信息比对验证咨询) 
阿里支付文档 https://opendocs.alipay.com/open/02qq4r
请求参数除了使用app_auth_token 应该还可以使用 auth_token 的形式进行调用
这个参数麻烦添加一下

**Comment by TIZ36** [comment]
解决了吗，好像最新版还是没有这个配置参数

**Comment by HaibaraAi123** [comment]
> 解决了吗，好像最新版还是没有这个配置参数

`
p := CertverifyConsultParam{
		AuthToken: accessToken,
		VerifyId:  certifyId,
	}
rsp := new(alipay.UserCertdocCertverifyConsultRsp)
err = client.DoRequest("POST", p, rsp)
`
自己创建个请求，然后调用client.DoRequest

**Comment by HaibaraAi123** [comment]
> 解决了吗，好像最新版还是没有这个配置参数

> 解决了吗，好像最新版还是没有这个配置参数

```
p := CertverifyConsultParam{
		AuthToken: accessToken,
		VerifyId:  certifyId,
	}
rsp := new(alipay.UserCertdocCertverifyConsultRsp)
err = client.DoRequest("POST", p, rsp)
```
自己创建个请求，然后调用client.DoRequest
