### ISSUE TITLE
type OpenAuthTokenApp struct  添加2个参数

### ISSUE THREAD

**Issue by 2810825** [smartwalle/alipay#158]
```
type OpenAuthTokenApp struct {
	GrantType    string `json:"grant_type"` // 值为 authorization_code 时，代表用code换取；值为refresh_token时，代表用refresh_token换取
	Code         string `json:"code"`
	RefreshToken string `json:"refresh_token"`
}

```
 OpenAuthTokenApp 换取应用授权令牌请求参数  新版有添加2个参数

1. State  自定义参数，授权后回调时透传回服务商。对应的值必须为 base64 编码。

2. AppTypes

 MOBILEAPP（移动应用）
WEBAPP（网页应用）
PUBLICAPP（生活号）
TINYAPP（小程序）
BASEAPP（基础应用）

**尤其 State参数可以返回时带上授权后进行绑定**

https://opendocs.alipay.com/isv/06evao?pathHash=f46ecafa
https://opendocs.alipay.com/isv/04h3ue?pathHash=0fec5099

**Comment by smartwalle** [comment]
你发的这个文档是 alipay.open.auth.appauth.invite.create 接口，我看了一下 OpenAuthTokenApp 接口的文档，并没有 state 和 apptypes 参数。
