### ISSUE TITLE
是否有解密方法？

### ISSUE THREAD

**Issue by musicode** [smartwalle/alipay#159]
[支付宝文档](https://opendocs.alipay.com/common/02mse3#AES%20%E8%A7%A3%E5%AF%86%E5%87%BD%E6%95%B0)

是否有此文档对应的解密函数呢？我搜了代码，好像没有

**Comment by smartwalle** [comment]
alipay.go 文件中 的 Client 结构体有一个 decrypt 的方法

**Comment by musicode** [comment]
@smartwalle 可是这个方法是私有的呢，外面访问不到

**Comment by smartwalle** [comment]
你在什么场景下需要单独进行解密？

**Comment by musicode** [comment]
小程序获取手机号这个场景，客户端传来是 response + sign，需要把 response 通过 aes key 解密出来

**Comment by smartwalle** [comment]
这个你能不能提供一份小程序端获取到的完整数据和密钥，我看看怎么集成进去。不行你就参考一下decrypt里面的代码，解密用到的是  github.com/smartwalle/ncrypto 库里面的 AESCBCDecrypt() 函数。

**Comment by musicode** [comment]
response

3UO4ElDwNFuhOg+3UVTlCaiHYgtPFis0EOEy/gBPRuCw1ZX4P5gNsbbATblw5LWfKsEpa5FuFwNUrz14E2Dr8Q==

sign

N8T+WmCZk5ulYd32bS9uR9KFYkTojqKaYKVAi3HFEp/6RrFrSMoRzD5J29OHfghlxoOe6ZG5Hf2ZKaxdtxURgY04YhmPbygS/l1ECJDmB2yGsPPaTbFP/o20QdpPmFriAVOiWwQLbnVUzm0uwb33zx38YUhyg8L9Rw/q0ts7ZQbIooJXg4JpLQ7cpAScxilRg1JnsTzmClz+UQbOTatnl8gz9NqyTStuAUXecVEOGR/nHMkO53WFkJw3TgAYEdWMclORBUoylQ3O+n8Dkq0uBrWoNQnm7921GUZ9QbrZjcE+zbkoxBfR1jxA7Pp78Pyy6eTVcfyZVO/xQfliBBm5nQ==

aes key

FywUuew48mvipAYW+NmZqg==

**Comment by musicode** [comment]
我还有一个问题，这个场景下，官网文档说要 『验签』，这个我也没找到相关方法

**Comment by smartwalle** [comment]
方不方便留一个 QQ 号码，我们 QQ 聊

**Comment by musicode** [comment]
280238215
