### ISSUE TITLE
会报这个github.com/smartwalle/ncrypto/pbkdf2 expects import "golang.org/x/crypto/pbkdf2"

### ISSUE THREAD

**Issue by zhushiqiang** [smartwalle/alipay#161]
如何解决的呢？

**Comment by smartwalle** [comment]
没遇到这种情况，你是没有用 mod 吗？

**Comment by zhushiqiang** [comment]
> 没有遇到这种情况，你没有用mod吗？
是的没有用，用的类似dep的工具，目前看对不支持mod的使用者 不太友好，我目前是fork到我的项目下，改了import "golang.org/x/crypto/pbkdf2"才能继续用

**Comment by smartwalle** [comment]
是一行注释代码的问题  😓
