### ISSUE TITLE
最新3.2.7编译失败

### ISSUE THREAD

**Issue by DevHaoZi** [smartwalle/alipay#162]
环境
Windows11
GO1.20
```
# github.com/smartwalle/alipay/v3
..\..\..\go\pkg\mod\github.com\smartwalle\alipay\v3@v3.2.6\alipay.go:139:24: undefined: nsign.New
..\..\..\go\pkg\mod\github.com\smartwalle\alipay\v3@v3.2.6\alipay.go:176:23: undefined: nsign.New
..\..\..\go\pkg\mod\github.com\smartwalle\alipay\v3@v3.2.6\alipay.go:481:56: undefined: nsign.WithIgnore
```

**Comment by smartwalle** [comment]
这种错误就是你本地没有对应的库

**Comment by wikylyu** [comment]
我在3.2.10也出现这个错误。我是用go mod管理的，go mod vendor是正常的，为啥编译的时候就出问题。

**Comment by DevHaoZi** [comment]
> 我在3.2.10也出现这个错误。我是用go mod管理的，go mod vendor是正常的，为啥编译的时候就出问题。

我的解决方法是通过`go get github.com/smartwalle/alipay/v3`更新，不要直接`go get -u`就没问题

**Comment by wikylyu** [comment]
> 

我单独更新alipay的话，会出现另外的错误

```golang
service/alipay/payment.go:60:9: cannot use _client.GetTradeNotification(req) (value of type *"github.com/smartwalle/alipay/v3".Notification) as *"github.com/smartwalle/alipay/v3".TradeNotification value in return statement
service/alipay/payment.go:74:65: r.Content undefined (type *"github.com/smartwalle/alipay/v3".TradeRefundRsp has no field or method Content)
service/alipay/payment.go:77:11: r.Content undefined (type *"github.com/smartwalle/alipay/v3".TradeRefundRsp has no field or method Content)
service/alipay/payment.go:86:14: r.Content undefined (type *"github.com/smartwalle/alipay/v3".FundTransUniTransferRsp has no field or method Content)
service/alipay/payment.go:88:80: r.Content undefined (type *"github.com/smartwalle/alipay/v3".FundTransUniTransferRsp has no field or method Content)
service/alipay/payment.go:91:52: r.Content undefined (type *"github.com/smartwalle/alipay/v3".FundTransUniTransferRsp has no field or method Content)
```

**Comment by DevHaoZi** [comment]
> > 
> 
> 我单独更新alipay的话，会出现另外的错误
> 
> ```go
> service/alipay/payment.go:60:9: cannot use _client.GetTradeNotification(req) (value of type *"github.com/smartwalle/alipay/v3".Notification) as *"github.com/smartwalle/alipay/v3".TradeNotification value in return statement
> service/alipay/payment.go:74:65: r.Content undefined (type *"github.com/smartwalle/alipay/v3".TradeRefundRsp has no field or method Content)
> service/alipay/payment.go:77:11: r.Content undefined (type *"github.com/smartwalle/alipay/v3".TradeRefundRsp has no field or method Content)
> service/alipay/payment.go:86:14: r.Content undefined (type *"github.com/smartwalle/alipay/v3".FundTransUniTransferRsp has no field or method Content)
> service/alipay/payment.go:88:80: r.Content undefined (type *"github.com/smartwalle/alipay/v3".FundTransUniTransferRsp has no field or method Content)
> service/alipay/payment.go:91:52: r.Content undefined (type *"github.com/smartwalle/alipay/v3".FundTransUniTransferRsp has no field or method Content)
> ```

看提交日志，最近更新的版本把Content去掉了

**Comment by letsfire** [comment]
好奇怪的设定。代码库用的是	github.com/smartwalle/nsign v0.0.1
如果go get -u更新的话会用到github.com/smartwalle/nsign v1.0.7，用这个就报错了

搞不懂，同一个库升级怎么这么不兼容。而且怎么还停留在使用0.0.1版本

**Comment by smartwalle** [comment]
试试   go get github.com/smartwalle/alipay/v3@v3.2.11
