### ISSUE TITLE
更换一下新版沙箱环境网关

### ISSUE THREAD

**Issue by zhushiqiang** [smartwalle/alipay#163]
![image](https://github.com/smartwalle/alipay/assets/17295335/fe45d233-c17a-45a1-99a1-0f2e654f9a5a)

**Comment by smartwalle** [comment]
https://github.com/smartwalle/alipay#%E6%B2%99%E7%AE%B1%E7%8E%AF%E5%A2%83%E7%BD%91%E5%85%B3%E5%9C%B0%E5%9D%80
