### ISSUE TITLE
package crypto/ecdh is not in GOROOT

### ISSUE THREAD

**Issue by wlbwlbwlb** [smartwalle/alipay#164]
when I upgraded to go1.19, an error occurred

**Comment by wlbwlbwlb** [comment]
details：github.com\smartwalle\ncrypto@v1.0.1\key.go:6:2: package crypto/ecdh is not in GOROOT

**Comment by smartwalle** [comment]
草率了，crypto/ecdh  这个库比较新。。。可以直接上  GOVERSION="go1.20.4"

**Comment by wlbwlbwlb** [comment]
got it, thanks
