### ISSUE TITLE
tradeapppay公钥证书+aes错误

### ISSUE THREAD

**Issue by ggdream** [smartwalle/alipay#169]
不使用aes key的时候没问题，setencryptkey的话就会参数错误。经支付宝人员排查，是aes加密的问题

**Comment by smartwalle** [comment]
你试试其它接口（比如 TradePreCreate）能不能正常访问；如果不能访问，确认你的 Key 是否正确。项目里面的测试是开启了内容加密的，目前没有发现有问题。

**Comment by linxun** [comment]
> 

+1

**Comment by smartwalle** [comment]
v3.2.15

**Comment by ccfish86** [comment]
我也遇到类似问题，不过我是使用的“小程序”的AppID，然后用小程序对应的AES密钥就不行，用`基础应用`设置的Aes密钥就可以。
![image](https://github.com/smartwalle/alipay/assets/15622514/32715763-6560-4536-ac3c-1672d63292c7)
