### ISSUE TITLE
同步数据验签，有做个测试吗

### ISSUE THREAD

**Issue by panjunjie** [smartwalle/alipay#17]
我看了你的代码很简洁，不知道兄台，对同步数据验签，有没有做过实际的测试？支持你的项目

**Comment by smartwalle** [comment]
是有做相关测试的，请参考 trade_test.go 文件中的 TestAliPay_TradeQuery 测试方法，可以修改 alipay_test.go 文件中 aliPublicKey 的内容来验证。

**Comment by panjunjie** [comment]
谢谢！
