### ISSUE TITLE
v3.2.15版本计算回调的sign时会对字段里的内容trim导致签名计算和alipay行为不一致

### ISSUE THREAD

**Issue by LuffyFeng** [smartwalle/alipay#179]
v3.2.15 签名实现
![image](https://github.com/smartwalle/alipay/assets/147354846/edaa145b-430a-4f16-89b1-bf595c38ecff)

v3.1.7 签名实现
![image](https://github.com/smartwalle/alipay/assets/147354846/421330da-9897-4ff1-b2c9-ec75358e5caa)

支付宝计算签名是会计算空格的，这里的trim会导致某些字段（如商品名称）首尾如果带了空格就会和支付宝计算的签名不一致，从而导致回调验证签名失败

**Comment by smartwalle** [comment]
![image](https://github.com/smartwalle/alipay/assets/909719/0dfe5ba9-daec-43b3-a334-953a2f17d97d)

商品名称是不影响签名的，商品名称属于图片中红色框中的内容，是“请求参数”的一部分，请求参数最终会序列化为 JSON 字符串，通过 biz_content 参数传递，而签名是对图片中蓝色框中的内容进行的。

你这边的问题可能不是由于这个点引起的。

**Comment by LuffyFeng** [comment]
比如我们遇到的是subject字段包含了尾空格

**Comment by smartwalle** [comment]
在 v3.2.19 版本中已经修复。
