### ISSUE TITLE
签约参数添加sign_notify_url

### ISSUE THREAD

**Issue by zyx9104** [smartwalle/alipay#180]
https://opendocs.alipay.com/support/01rg34
签约的请求参数里面没有notify_url，是sign_notify_url

**Comment by smartwalle** [comment]
https://github.com/smartwalle/alipay/blob/cf2259bfb863f72f58e548c45534d7a7f3c8f53a/trade_type.go#L51  

代码中是 sign_notify_url

**Comment by zyx9104** [comment]
> https://github.com/smartwalle/alipay/blob/cf2259bfb863f72f58e548c45534d7a7f3c8f53a/trade_type.go#L51
> 
> 代码中是 sign_notify_url

https://github.com/smartwalle/alipay/blob/cf2259bfb863f72f58e548c45534d7a7f3c8f53a/user_type.go#L46C31-L46C32
这里没有，这两个有啥区别
