### ISSUE TITLE
签名验证失败问题

### ISSUE THREAD

**Issue by wwwAngHua** [smartwalle/alipay#186]
我使用 `alipay.TradePreCreate{}` 生成订单，它是能够正常返回付款URL付款的（当面付），但是我使用 `aliPay_client.DecodeNotification` 验证签名，请求是支付宝服务器发出的，但却一直验证失败，是什么原因？

完整代码

```go
var aliPay_client, aliPay_err = alipay.New(ap[0].AlipayID, ap[0].AlipayPrivateKey, isSandbox(ap[0].Sandbox))
aliPay_client.LoadAliPayPublicKey(ap[0].AlipayPublicKey)
if aliPay_err != nil {
	return false
}
if err := ctx.Request.ParseForm(); err != nil {
	return false
}
var _, err = aliPay_client.DecodeNotification(ctx.Request.Form)
if err != nil {
	return false
}
alipay.ACKNotification(ctx.Writer)
return true
```

**Comment by smartwalle** [comment]
你提供给支付宝的回调url是否其它参数？

**Comment by smartwalle** [comment]
看看这一行有没有返回错误  aliPay_client.LoadAliPayPublicKey(ap[0].AlipayPublicKey)

**Comment by smartwalle** [comment]
看一下是那个 err 导致的返回 false

**Comment by smartwalle** [comment]
ap[0].AlipayPublicKey   这个公钥是哪里来的？

**Comment by smartwalle** [comment]
你成功调用过  alipay.TradePreCreate 这个接口，可以明确签名验证功能是没有问题的。不确定是不是数据的原因，或者你使用 master 分支试试。

**Comment by smartwalle** [comment]
那个字符确实有问题，不知道是输出的问题，还是确实存在，自己追踪一下吧。
