### ISSUE TITLE
alipay.open.mini.baseinfo.modify(小程序修改基础信息)

### ISSUE THREAD

**Issue by feng003** [smartwalle/alipay#194]
alipay.open.mini.baseinfo.modify  这个接口因为需要上传一个 logo 图片
所以使用[自定义文件上传](https://github.com/smartwalle/alipay#%E6%96%87%E4%BB%B6%E4%B8%8A%E4%BC%A0)

p.AddParam("app_name", "小程序名字")
p.AddParam("app_slogan", "小程序简介")

但同时需要添加其他参数的传递，会出现一个问题就是中文编码格式不对，传给支付宝的时候会出现乱码
想请教一下这个地方有没有好的处理方式？

**Comment by smartwalle** [comment]
接口能够调用成功吗？如果能够调用成功，并且只是乱码，尝试一下传递英文试试呢？

**Comment by smartwalle** [comment]
如果英文可以，就试一下下面这种方式：
p.AddParam("app_slogan", url.QueryEscape("小程序简介"))

**Comment by feng003** [comment]
> 接口能够调用成功吗？如果能够调用成功，并且只是乱码，尝试一下传递英文试试呢？

接口传参数是英文的话 是可以调用的

**Comment by feng003** [comment]
> 如果英文可以，就试一下下面这种方式： p.AddParam("app_slogan", url.QueryEscape("小程序简介"))

使用编码的话，感觉支付宝那边接受没有进行解码，所以那边会显示编码的数据，而不是中文，我先试试，谢谢了
