### ISSUE TITLE
alipay.user.deloauth.detail.query(查询解除授权明细) 这个api 有吗

### ISSUE THREAD

**Issue by a767511165** [smartwalle/alipay#196]

**Comment by smartwalle** [comment]
没有哦

**Comment by smartwalle** [comment]
可参考 https://github.com/smartwalle/alipay?tab=readme-ov-file#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%AF%B7%E6%B1%82

**Comment by a767511165** [comment]
好的，多谢&nbsp;


ぃ&nbsp;殇.★无奈
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年3月18日(星期一) 下午3:28
收件人: ***@***.***&gt;; 
抄送: "ぃ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [smartwalle/alipay] alipay.user.deloauth.detail.query(查询解除授权明细) 这个api 有吗 (Issue #196)





 
可参考 https://github.com/smartwalle/alipay?tab=readme-ov-file#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%AF%B7%E6%B1%82
