### ISSUE TITLE
AliPay.publicKey 在New的时候被赋值了但是未被使用

### ISSUE THREAD

**Issue by zwh8800** [smartwalle/alipay#20]
你好，首先感谢开发出这个SDK，很好用。

我在使用时发现，调用 alipay.New 时会传入 publicKey，但是 publicKey 变量仅仅做了赋值操作，在后续的代码中并没有被使用到，而是使用了 AliPay.AliPayPublicKey 字段作为验签的公钥。感觉这样使用起来并不是很直观，请问这么设计是有意为之还是bug呢？

谢谢

**Comment by smartwalle** [comment]
publicKey 就现在来看，确实是没有任何作用的。

**Comment by zwh8800** [comment]
了解了，我之前把 AliPayPublicKey 和商户的 publicKey 搞混了
