### ISSUE TITLE
input context support otel

### ISSUE THREAD

**Issue by mingzaily** [smartwalle/alipay#200]
能否支持传入context对象，并支持otel链路跟踪
我翻之前的issue，之前有个同学提到了，作者标记complete但我还是没翻到使用方法

**Comment by smartwalle** [comment]
添加 context 参数没有问题，但是追踪在这种库中意义不大。

**Comment by mingzaily** [comment]
那先支持context吧，otel我看了下其实可以在smartwalle/ngx库加一个span记录就行，我后面有空提个pr

**Comment by smartwalle** [comment]
欢迎

**Comment by mingzaily** [comment]
我现在在想如何将log引入进来，是定义一个log interface？但不知道常用的log库能否直接实现
