### ISSUE TITLE
验签失败，请指点下

### ISSUE THREAD

**Issue by jdongdong** [smartwalle/alipay#21]
请教下，我在使用的时候一直验签不过，报错信息如下：
`crypto/rsa: verification error`

采用的是RSA2加密方式
库是采用最新版本
调用接口为：alipay.trade.precreate (统一收单线下交易预创建)

返回的验签数据如下：
`{"code":"10000","msg":"Success","sub_code":"","sub_msg":"","out_trade_no":"123456789","qr_code":"https://qr.alipay.com/bax06556bw4qmhfcofn500a4"}`
sign
`JJLTxJM0T636iTPriJ7pUFikznjFZvQIilNUQI80AkReb3rHVxFpZzxhvG99G3Ms8pt0ePSPBAVonDYOOPUkcfGh
+sCmVAAfZWY/IRlUB/F6Jw3N1NU9GxTbiGS2Q2VVpurIaRq5T8HTorbuUTHbeRM6/aut7H5QuP5o1lOhBOW0nKRVP3dhb/Xx0HP2c2E+6Edxl3TByLvVbqP3fpmxP58GBUbkHSUcEb8ShUB7M/l4pKy3u5dti4zeW3SWBqScZiH2mQbectrUY1n3uPromohiQmIfocviBGxATPj4nMzuKoDtl2Fuvp4TUctxBJNg2Z
s2B64I2e93GUywMfwqEQ==`

支付宝公钥：
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqnjvtwG/VsfPReiaOhHt
Hbfu93W2RrSAJ61Hgod4M2iT78mD9tS/Wn7n7CxOR6I95pI8OAih8wCbNpx7bvFj
q/KvjNeXCIqXwqUA6BtaT/ECDZLijtV9Xvtr8TMVm+FXr59HQw8urdFpC+lUx/ZW
bgWtyIFIhvxdUNjmuXHV34FzN5A94N2fk75E9UOH8XF3Q2jWmUF5tM/cznBzQ/B9
SP0+0AjnzKQgeF65lF7pi8CcBVlU3IOuJNAZHRAZBDVZxOEOoXKfCGiFN6njlzcC
gbjpuyMF4WnK9ihCMcr3Lntjg6TWtVtXQbh6RWu9b5Jz+zjYUKlafAYAvU5JE6Wi
FwIDAQAB
-----END PUBLIC KEY-----

**Comment by jdongdong** [comment]
您好，我找到问题在哪了，有两个问题

- url中/需要转义成\/
- 待签参数中sub_code与sub_msg不参与签名

请问下这是个bug还是需要自行验签，如果是需要自行验签的话那库中自带验签功能是针对什么场景才有效的呢

**Comment by smartwalle** [comment]
您好，我用沙盒环境进行测试，能够成功验签，我提供了测试用例，你可以更新项目然后 test 一下。

**Comment by smartwalle** [comment]
https://doc.open.alipay.com/docs/doc.htm?docType=1&articleId=106120   参考支付宝的文档，有一句说明 “1.在通知返回参数列表中，除去sign、sign_type两个参数外，凡是通知返回回来的参数皆是待验签的参数。” ， 所以 sub_code与sub_msg 是需要参与验签的；关于url，返回的字符串本来就是 \/, 只不过最后json.Unmarshal() 转换为 struct 之后，是经过处理的，所以你看到的是 /，但是参与验签的是 \/。

**Comment by panjunjie** [comment]
谢谢作者，很棒！

**Comment by jdongdong** [comment]
非常感谢，问题解决了，是因为自己用json.Marshal解析的时候多解析出sub_code和sub_msg字段
