### ISSUE TITLE
undefined: AliPayTradePagePay

### ISSUE THREAD

**Issue by goodforever** [smartwalle/alipay#24]
go test trade.go 
# command-line-arguments
./trade.go:10: undefined: AliPay
./trade.go:10: undefined: AliPayTradePagePay
./trade.go:33: undefined: AliPay
./trade.go:33: undefined: AliPayTradeQueryResponse
./trade.go:33: undefined: AliPayTradeQuery
./trade.go:39: undefined: AliPay
./trade.go:39: undefined: AliPayTradeCloseResponse
./trade.go:39: undefined: AliPayTradeClose
./trade.go:45: undefined: AliPay
./trade.go:45: undefined: AliPayTradeRefundResponse
./trade.go:45: too many errors

**Comment by smartwalle** [comment]
直接 go test 即可，后面不要加文件

**Comment by goodforever** [comment]
我在我的程序里用	var p = AliPayTradePagePay{}的时候也是undefined: AliPayTradePagePay

**Comment by smartwalle** [comment]
我觉得应该是和 go path 有关系，建议你多尝试一下

**Comment by goodforever** [comment]
你go test trade_test.go 正常吗？

**Comment by smartwalle** [comment]
在某一个包下面执行 go test，默认对象是这个包下的所有源代码文件；如果 go test  file.go ，那在 test 的时候就只是针对这一个文件，因为这个项目的test文件和源代码是放在一个包下，所以在 test 文件中并不需要单独的导入相关的包，所以你go test trade_test.go 会报各种undefined, 去好好检查一下你的代码，要么是包引入错误，要么就是go path 设置有问题

**Comment by goodforever** [comment]
我是：
go get github.com/smartwalle/alipay
cd github.com/smartwalle/alipay
go test OK
go test trade_test.go 
# command-line-arguments
./trade_test.go:22: undefined: AliPayTradeQuery
./trade_test.go:25: undefined: client in client.TradeQuery
./trade_test.go:36: undefined: AliPayTradeAppPay
./trade_test.go:43: undefined: client in client.TradeAppPay
./trade_test.go:49: undefined: AliPayTradePagePay
./trade_test.go:56: undefined: client in client.TradePagePay
也就是在你的源码目录下，无任何我的代码，我别的github.com/xxx/xxx及自己的项目都正常，go path应没问题。请问在你的系统中 go test trade_test.go 没问题吗？

**Comment by smartwalle** [comment]
请仔细看我的上一条回复

**Comment by smartwalle** [comment]
或者加我qq   917996695
