### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by misasky** [smartwalle/alipay#31]
(*´▽｀)ノノ你好，想问一下各位大佬，wap支付的参数对了，为什么返回的url是这个：https://openapi.alipaydev.com/gateway.do。app支付用了挺好用的

**Comment by smartwalle** [comment]
我刚刚用sandbox环境测试的时候，偶尔会出现类似的情况，具体原因暂时不清楚，如果有条件，建议你使用 production 环境测试一下。

**Comment by misasky** [comment]
我直接用在项目里了呢，不是沙箱测试的结果，每次都是返回的 https://openapi.alipaydev.com/gateway.do 
这个地址呢，传的参数是五个，您文档上写的参数

**Comment by smartwalle** [comment]
那你看看第五个参数是 false 还是 true，生产环境第五个参数应该为 true

**Comment by misasky** [comment]
好的，解决了，应该是沙箱环境有问题导致的，谢谢大佬
