### ISSUE TITLE
cannot use req (type *http.Request) as type url.Values in argument to verifySign

### ISSUE THREAD

**Issue by songyixu** [smartwalle/alipay#35]
Yis-MacBook-Pro:main yixusong$ go build
# github.com/smartwalle/alipay
../../../../smartwalle/alipay/notify_type.go:92:23: cannot use req (type *http.Request) as type url.Values in argument to verifySign

**Comment by smartwalle** [comment]
更新一下代码

**Comment by songyixu** [comment]
好了，多谢
On 11 Apr 2018, at 7:30 AM, 杨烽 <notifications@github.com<mailto:notifications@github.com>> wrote:


更新一下代码
