### ISSUE TITLE
请问官方文档上直接输出Response到HTML跟这个项目的区别是？

### ISSUE THREAD

**Issue by ghost** [smartwalle/alipay#47]
我看了下，这个项目使用的是按参数组合URL，
官方现在文档上是从服务端获取表单内容然后直接输出到商户页面里面，
这两者实现的区别是什么？
这项目的实现方式是否为支付宝接口1.0？
如果是按1.0的老版本接口实现的话，那么这个项目的兼容性是否在将来会有问题？

**Comment by smartwalle** [comment]
你看的是那个文档？

**Comment by Chocky99** [comment]
`public void doPost(HttpServletRequest httpRequest,
                      HttpServletResponse httpResponse) throws ServletException, IOException {
    AlipayClient alipayClient = new DefaultAlipayClient("https://openapi.alipay.com/gateway.do", APP_ID, APP_PRIVATE_KEY, FORMAT, CHARSET, ALIPAY_PUBLIC_KEY, SIGN_TYPE); //获得初始化的AlipayClient
    AlipayTradePagePayRequest alipayRequest = new AlipayTradePagePayRequest();//创建API对应的request
    alipayRequest.setReturnUrl("http://domain.com/CallBack/return_url.jsp");
    alipayRequest.setNotifyUrl("http://domain.com/CallBack/notify_url.jsp");//在公共参数中设置回跳和通知地址
    alipayRequest.setBizContent("{" +
        "    \"out_trade_no\":\"20150320010101001\"," +
        "    \"product_code\":\"FAST_INSTANT_TRADE_PAY\"," +
        "    \"total_amount\":88.88," +
        "    \"subject\":\"Iphone6 16G\"," +
        "    \"body\":\"Iphone6 16G\"," +
        "    \"passback_params\":\"merchantBizType%3d3C%26merchantBizNo%3d2016010101111\"," +
        "    \"extend_params\":{" +
        "    \"sys_service_provider_id\":\"2088511833207846\"" +
        "    }"+
        "  }");//填充业务参数
    String form="";
    try {
        form = alipayClient.pageExecute(alipayRequest).getBody(); //调用SDK生成表单
    } catch (AlipayApiException e) {
        e.printStackTrace();
    }
    httpResponse.setContentType("text/html;charset=" + CHARSET);
    httpResponse.getWriter().write(form);//直接将完整的表单html输出到页面
    httpResponse.getWriter().flush();
    httpResponse.getWriter().close();
}`


https://docs.open.alipay.com/270/105899/
示例代码是从上面这个URL里面复制的，倒数第三句

**Comment by smartwalle** [comment]
你有兴趣可以看看他的form是什么内容。

**Comment by smartwalle** [comment]
我个人的理解，他这个是调用了 alipay.trade.page.pay 这个接口，然后将返回的html直接输出到浏览器，这个和我提供的库的处理方式本质上是一样的，只不过一个是服务器端去调用的 alipay.trade.page.pay，一个是直接交由浏览器端去调用之后跳转。
