### ISSUE TITLE
手机app订单签名失败

### ISSUE THREAD

**Issue by shiqinfeng1** [smartwalle/alipay#49]
执行client.TradeAppPay(p)后，失败信息为：
asn1: structure error: tags don't match (2 vs {class:0 tag:16 length:13 isCompound:true}) {optional:false explicit:false application:false defaultValue:\u003cnil\u003e tag:\u003cnil\u003e stringType:0 timeType:0 set:false omitEmpty:false}  @5

已检查私钥公钥是ok的。 查看历史issue，之前也有人遇到了这个问题，可以确定是签名的问题，那位兄弟是更换go版本后解决了， 我使用go1.10版本， 跟踪了下代码，发现返回错误的地方如下：
```
func SignPKCS1v15(src, key []byte, hash crypto.Hash) ([]byte, error) {
	var h = hash.New()
	h.Write(src)
	var hashed = h.Sum(nil)

	var err error
	var block *pem.Block
	block, _ = pem.Decode(key)
	if block == nil {
		return nil, errors.New("private key error")
	}

	var pri *rsa.PrivateKey
	pri, err = x509.ParsePKCS1PrivateKey(block.Bytes)
	if err != nil {
		return nil, err
	}
       ... ...
```
具体出错的代码是： pri, err = x509.ParsePKCS1PrivateKey(block.Bytes)， 该err为asn1: structure error: tags don't match。。。

补充：已跟踪到下面的代码问题， asn1.Unmarshal 失败了：
```
ParsePKCS1PrivateKey(der []byte) (*rsa.PrivateKey, error) {
	var priv pkcs1PrivateKey
	rest, err := asn1.Unmarshal(der, &priv)
```

我的环境信息：
# go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/shiqinfeng/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/shiqinfeng/Documents/go_workspace"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/1p/c_0vpz0j47sb4cvvwppl04mw0000gn/T/go-build629607236=/tmp/go-build -gno-record-gcc-switches -fno-common"

# go version
go version go1.10.2 darwin/amd64

**Comment by smartwalle** [comment]
这个问题可能是因为你的 密钥对是 PKCS8 的，转成PKCS1 的试一下。

**Comment by shiqinfeng1** [comment]
是这个原因，谢谢！

**Comment by xiaxianmao** [comment]
> 这个问题可能是因为你的 密钥对是 PKCS8 的，转成PKCS1 的试一下。

支付宝提供了 pkcs8 转 pkcs1 的工具
https://docs.open.alipay.com/291/106097
