### ISSUE TITLE
无法使，结果如下，求解。

### ISSUE THREAD

**Issue by gujunyan** [smartwalle/alipay#51]
1、TradeWapPay  返回一个url有何用？原支付宝SDK是返回一个body，再把body response回到浏览器内执行。
2、为何现行网站上ProductCode 是 QUICK_WAP_WAY  而不是当前这个SDK内的值？
3、调完后，返回的内容是 

 “原来浏览器版本低是硬伤！
建议使用UC、Chrome、IE10等高版本浏览器”

不解

**Comment by smartwalle** [comment]
1、服务器端直接重定向到该 url 即可，或者把该 url 返回给前端，前端重定向；
2、支付宝网站写的是 QUICK_WAP_WAY；

**Comment by gouez** [comment]
始终返回的URL是https://openapi.alipaydev.com/gateway.do  怎么回事？

**Comment by smartwalle** [comment]
你的参数有问题

**Comment by gouez** [comment]
我仔细比对了下参数，发现url.Values.Encode()方法会把2006-01-02 15:04:05转为2006-01-02+15:04:05

**Comment by smartwalle** [comment]
你可以先参考一下 test 文件里面的处理，里面的测试都是可以直接运行的。
