### ISSUE TITLE
关于alipay.trade.wap.pay接口的Subject中文参数

### ISSUE THREAD

**Issue by connorgame** [smartwalle/alipay#56]
alipay.trade.wap.pay接口的Subject参数是中文时，接口调用返回的url用浏览器打开后进行支付时订单信息显示乱码是怎么解决的？

**Comment by connorgame** [comment]
懂了

**Comment by feng003** [comment]
懂了  啥意思  有没有解决方法，好几个地方出现 返回值的中文都是乱码呢
