### ISSUE TITLE
线上资金授权冻结接口 未完全支持

### ISSUE THREAD

**Issue by MaxnSter** [smartwalle/alipay#58]
https://github.com/smartwalle/alipay/blob/a68491d910bfaf8a0cff6aad78c89b780d6b0b65/fund.go#L54

没有发起请求

**Comment by smartwalle** [comment]
主要是那一部分有缺失呢

**Comment by MaxnSter** [comment]
> 主要是那一部分有缺失呢

这个func仅仅实现了 ```URLValues```，都没有发起http请求，不完整...

完整的接口实现，应该和下面这个func类似吧

https://github.com/smartwalle/alipay/blob/a68491d910bfaf8a0cff6aad78c89b780d6b0b65/fund.go#L33

**Comment by smartwalle** [comment]
这个接口应该是生成参数给app用的，有另一个接口是可以直接调用的。

**Comment by MaxnSter** [comment]
嗯，看了下，我直接调用DoRequest也可以。感谢答复 :smile: :smile:

**Comment by MaxnSter** [comment]
更正，是我理解错了。调用FundAuthOrderAppFreeze后将result传给客户端，客户端根据orderStr拉起支付宝。

**Comment by lazyderek** [comment]
FundAuthOrderAppFreeze生成orderStr就可以了？不需要先向支付宝创建支付单么？

**Comment by lazyderek** [comment]
能说一下调用方法么？看不太懂
