### ISSUE TITLE
TradeAppPay报错

### ISSUE THREAD

**Issue by thathappiness** [smartwalle/alipay#59]
asn1: structure error: tags don't match (2 vs {class:0 tag:16 length:13 isCompound:true}) {optional:false explicit:false application:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false}  @5

**Comment by smartwalle** [comment]
你的密钥有问题。换成 pkcs1 的

**Comment by thathappiness** [comment]
是pkcs1的，之前用支付宝提供的工具生成的2048位的，PHP的代码可以成功对接支付宝接口，是不是长度必须是1024位才行？

**Comment by thathappiness** [comment]
不好意思，确实是密钥问题，之前密钥不是pkcs1格式的，谢谢！
