### ISSUE TITLE
线上资金授权冻结接口 AppAuthToken为空时，生成的result字符串有误

### ISSUE THREAD

**Issue by MaxnSter** [smartwalle/alipay#60]
注释[该行](https://github.com/smartwalle/alipay/blob/a68491d910bfaf8a0cff6aad78c89b780d6b0b65/fund_type.go#L403) 后，客户端才可以拉起支付宝

**Comment by smartwalle** [comment]
已提交新的代码，麻烦帮忙再验证一下。

**Comment by MaxnSter** [comment]
> 已提交新的代码，麻烦帮忙再验证一下。

使用最新代码后，问题解决
