### ISSUE TITLE
授权转支付接口，缺少auth_no参数

### ISSUE THREAD

**Issue by MaxnSter** [smartwalle/alipay#62]
[文档](https://docs.open.alipay.com/20180417160701241302/qca164/)中的 
```
model.setAuthNo("2018041210002001660228733635"); // 填写预授权冻结交易号
```
AliPayTradePay这个struct中没有这个字段，刚开始误以为是AuthCode，后来把AuthCode的tag改为auth_no，接口才成功返回

**Comment by smartwalle** [comment]
你说的这个参数在文档  https://docs.open.alipay.com/api_1/alipay.trade.pay 中并未提及

**Comment by smartwalle** [comment]
具体是那一个接口的问题呢？

**Comment by MaxnSter** [comment]
就是https://docs.open.alipay.com/api_1/alipay.trade.pay 
只是在授权转支付这个场景下，只能使用[这个方式](https://docs.open.alipay.com/20180417160701241302/qca164/)来传参，这需要个`auth_no`参数，但是 https://docs.open.alipay.com/api_1/alipay.trade.pay 里未提及...

**Comment by smartwalle** [comment]
提交了更新，你可以更新代码再试一下。

**Comment by MaxnSter** [comment]
问题解决了
