### ISSUE TITLE
请问TradeWapPay为什么是服务端提交请求

### ISSUE THREAD

**Issue by kpvt001** [smartwalle/alipay#67]
wap.go文件里，TradeWapPay在服务端直接做了提交请求，难道不是由客户端提交的吗

**Comment by smartwalle** [comment]
主要是为了安全，服务器端获取到支付的链接地址后发给客户端，可以避免把相关的key等信息放在客户端引起重要信息泄露

**Comment by kpvt001** [comment]
谢谢，还有一个问题，那就是NotifyVerify的作用是什么？目前在alipay.trade.app.pay和alipay.trade.wap.pay文档里的返回参数均看不到notify_id参数

**Comment by kpvt001** [comment]
好的谢谢
