### ISSUE TITLE
 "golang.org/x/crypto/pbkdf2"找不到此包

### ISSUE THREAD

**Issue by clearluo** [smartwalle/alipay#7]
$ go get -u github.com/smartwalle/alipay
package golang.org/x/crypto/pbkdf2: unrecognized import path "golang.org/x/crypto/pbkdf2" (https fetch: Get https://golang.org/x/crypto/pbkdf2?go-get=1: dial tcp 216.239.37.1:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.)

**Comment by smartwalle** [comment]
这个包是golang团队提供的，需要科学上网获取哈。

**Comment by smartwalle** [comment]
https://github.com/golang  这里也有golang官方包的镜像。

你可以 go get github.com/golang/crypto，然后在 GO PATH 的 src 目录下依次创建 golang.org/x 文件夹，然后将 github.com/golang 下的 crypto 文件夹移动到 golang.org/x 目录下。
