### ISSUE TITLE
查询返回无解析buyer_user_name

### ISSUE THREAD

**Issue by libra1010** [smartwalle/alipay#85]
查询接口文档标注有一个选填字段 buyer_user_name
发现没有解析返回，是否有考虑加入？
或者说多余的字段提供原始数据访问的功能？

**Comment by smartwalle** [comment]
是那一个接口，文档地址发一下呢

**Comment by libra1010** [comment]
> 是那一个接口，文档地址发一下呢

https://docs.open.alipay.com/api_1/alipay.trade.query/
![image](https://user-images.githubusercontent.com/9667153/63661426-1715ec00-c7ed-11e9-9c5c-7a360ad094c3.png)
建议常用的解析成为字段直接使用。在返回一个附加的map,里面就是全部的返回字段和value。
只是一个建议而已

**Comment by smartwalle** [comment]
v3 和 v2.0.11 已添加本字段
