### ISSUE TITLE
alipay.trade.app.pay

### ISSUE THREAD

**Issue by huncent** [smartwalle/alipay#9]
有计划集成
alipay.trade.app.pay接口吗？

**Comment by smartwalle** [comment]
你好，已经添加对 alipay.trade.app.pay 接口。

我并没有实际使用过该接口，从网上文档了解到，该接口服务器端只是返回对相关参数的编码及签名，然后由 APP 端的 SDK 使用服务器端处理好的数据进行支付请求。

**Comment by huncent** [comment]
测试通过

**Comment by panjunjie** [comment]
此接口RSA2 方式，sign 生成 是空字符串，返回参数如下：
app_id=2015082000223895&biz_content={"body":"iPhone7 ","subject":"iPhone7 ","out_trade_no":"20170531220","timeout_express":"90m","total_amount":"1.00","seller_id":"1011007","product_code":"QUICK_MSECURITY_PAY"}&charset=utf-8&format=JSON&method=alipay.trade.app.pay&notify_url=https://service.lalawitkey.com/alipay/pay/trade_notify2&sign=&sign_type=RSA2&timestamp=2017-05-31 02:24:23&version=1.0

**Comment by panjunjie** [comment]
```
   app_id=2015082000223895&biz_content={"body":"iPhone7 一元抢购","subject":"iPhone7 一元抢购","out_trade_no":"20170531220","timeout_express":"90m","total_amount":"1.00","seller_id":"10007","product_code":"QUICK_MSECURITY_PAY"}&charset=utf-8&format=JSON&method=alipay.trade.app.pay&notify_url=https://service.lalawitkey.com/alipay/pay/trade_notify2&sign=&sign_type=RSA2&timestamp=2017-05-31 02:24:23&version=1.0
```

**Comment by huncent** [comment]
@panjunjie 估计你调用方式不对吧？这个本身就推荐RSA2，所以我的测试也是RSA2下通过的
