### ISSUE TITLE
对数组的参数组装有问题

### ISSUE THREAD

**Issue by Anderson-Lu** [smartwalle/alipay#92]
type Param interface {
	// 用于提供访问的 method
	APIName() string

	// 返回参数列表
	Params() map[string]string
}

这里的 map[string]string 会导致biz_content里边的数组变成一个字符串

**Comment by smartwalle** [comment]
具体是那一个接口的那一个字段

**Comment by shoaly** [comment]
应该也是我提的那个 issue 类似,  https://github.com/smartwalle/alipay/issues/120
ExtendParams 是其中一个,  朋友也说一下你发现的是那个字段
