### ISSUE TITLE
关于普通公钥的去除

### ISSUE THREAD

**Issue by diemus** [smartwalle/alipay#93]
我记得支付宝官方文档里提到，个人开发者由于不涉及资金的转出，建议用普通公钥的形式。我看V3版本去除了对普通公钥的支持，这个是不是有些过于替使用者做决定了。虽然v2版本可以使用，但是这个分支已经不维护了，v3版本如果需要使用普通证书，有什么别的方法吗？

**Comment by smartwalle** [comment]
v3版本添加了对普通公钥的支持
