### ISSUE TITLE
 README文档误导#异步验证支付结果

### ISSUE THREAD

**Issue by yann0917** [smartwalle/alipay#99]
`GetTradeNotification` 这个方法返回的只是支付宝的异步通知，
并不能根据 `noti ` 判断支付成功， 而是根据 `noti.TradeStatus` 判断是否支付成功

![image](https://user-images.githubusercontent.com/25262709/72202016-9bfc5c00-3495-11ea-81f7-834ada482f4d.png)

[支付结果异步通知](https://docs.open.alipay.com/203/105286)

**Comment by smartwalle** [comment]
已更新文档

**Comment by yann0917** [comment]
> 已更新文档

还不太对：

>在支付宝的业务通知中，只有交易通知状态为`TRADE_SUCCESS`或`TRADE_FINISHED`时，支付宝才会认定为买家付款成功。

- 状态`TRADE_SUCCESS`的通知触发条件是商户签约的产品支持退款功能的前提下，买家付款成功；
- 交易状态`TRADE_FINISHED`的通知触发条件是商户签约的产品不支持退款功能的前提下，买家付款成功；或者，商户签约的产品支持退款功能的前提下，交易已经成功并且已经超过可退款期限。
